version: "3.9"  # optional since v1.27.0
services:
  web_api:
    #image: todobackendapi
    build: .
    container_name: todobackendapi
    ports:
      - "5001:443"
      - "5000:80" 
    volumes: 
      - ~/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=todoc3rtp@ssword1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ToDoBackend.Api.pfx
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=tododbacc3ss@!